server:
  host: localhost
  port: 9090

rabbitmq:
  protocol: 'amqp'
  hostname: '192.168.182.75'
  port: 5672
  username: '1900'
  password: '123456'
  vhost: '/1900'

crypto:
  # 秘钥
  key: "1111111111111111"
  # 偏移量
  iv: "adlskjgityuhdijk"
